package com.macrotel.rapidstylers.outbox;

public enum OutboxEventType {
    BOOKING_REQUESTED,
    BOOKING_CONFIRMED,
    BOOKING_DECLINED,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED,
    PAYMENT_INTENT_CREATED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    REFUND_REQUESTED,
    CUSTOMER_WELCOME,
    REFUND_COMPLETED,
    EMAIL_REQUESTED,
    SMS_REQUESTED,
    NOTIFICATION_REQUESTED
}
